services:
  - type: web
    name: laravel-app
    plan: free
    region: frankfurt
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0vbpiu3jp1c73e0kfp0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: b1
      - key: DB_USERNAME
        value: postgres1
      - key: DB_PASSWORD
        value: O4rKMTmZPmPXK80mBvv0OkSTPOCRkasf
      - key: APP_KEY
        value: base64:AqcsAKR+oLMBMwFMxONS0S/OLad2pkxln2ue5iPfoiY=
